### PR TITLE
Update to nom 6.x

### PR DESCRIPTION
**Pull request by tweksteen**
This is an upgrade to nom 6.x. It was tested via `cargo test`. @jethrogb Could you please review? Could you please also consider adding @emilio as maintainer (see #23)? Thanks.

Old obsolete message:
> This is an attempt at upgrading to nom 6.x. There is still an issue in `typed_token` about the expected lifetime of the input. @jonhoo, since you did the port to nom 5.x, you may have some insight on how to fix this.
@jethrogb, any feedback is appreciated. Thanks.

Bug: #26

### CODE REVIEW

**Comment by jethrogb** [comment]
I don't understand bors. But try now.

**Comment by emilio** [comment]
Seems to be doing stuff, thanks @jethrogb!

**Comment by tweksteen** [comment]
Thanks!

**Pull request merged**
